###################
### MY WALLPAPER ###
###################
preload = $HOME/Pictures/astronaut-surreal.jpg
wallpaper = , $HOME/Pictures/astronaut-surreal.jpg

### Wallpaper 2 ###
# preload = $HOME/Pictures/samurai.png
# wallpaper = , $HOME/Pictures/samurai.png

