###################
### MY WALLPAPER ###
###################
# preload = $HOME/Pictures/astronaut-surreal.jpg
# wallpaper = , $HOME/Pictures/astronaut-surreal.jpg

### Wallpaper 2 ###
preload = $HOME/Pictures/firehouse.jpg
wallpaper = , $HOME/Pictures/firehouse.jpg

