 # You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf

### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
# monitor=,preferred,auto,auto
monitor = eDP-1,preferred,0x0,auto
monitor = DP-1,preferred,0x-1080,auto
###To mirror monitor###
# monitor = DP-1,preferred,0x-1080,auto,mirror,eDP-1
monitor = WAYLAND-1, disable

# Any unknown monitors (future external displays)
monitor = ,preferred,auto,auto


# Assign workspaces 1-5 to monitor eDP-1 (or whatever your first monitor is)
workspace=1,monitor:eDP-1
workspace=2,monitor:eDP-1
workspace=3,monitor:eDP-1
workspace=4,monitor:eDP-1
workspace=5,monitor:eDP-1

# Assign workspaces 6-10 to monitor HDMI-A-1 (or your second monitor)
workspace=6,monitor:DP-1
workspace=7,monitor:DP-1
workspace=8,monitor:DP-1
workspace=9,monitor:DP-1
workspace=10,monitor:DP-1
###################
### MY PROGRAMS ###
###################


# Set programs that you use
$terminal = ghostty
$fileManager = nautilus --new-window
$browser = chromium --new-window --ozone-platform=wayland
$music = spotify
$webapp = $browser --app
$browser1 = firefox-developer-edition --browser

source = ~/.config/hypr/extra/envs.conf
source = ~/.config/hypr/extra/autostart.conf
source = ~/.config/hypr/extra/looknfeel.conf
source = ~/.config/hypr/extra/input.conf
source = ~/.config/hypr/extra/bindings.conf

# Extra bindings
bind = SUPER, A, exec, $webapp="https://chatgpt.com"
bind = SUPER SHIFT, A, exec, $webapp="https://claude.ai"
bind = SUPER SHIFT, G, exec, $webapp="https://grok.com"
bind = SUPER, Y, exec, $webapp="https://youtube.com/"
bind = SUPER, G, exec, $webapp="https://web.whatsapp.com/"
bind = SUPER, X, exec, $webapp="https://x.com/"

##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
