
#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = sh ~/.config/hypr/launch_waybar.sh 

# Waybar reload binds
bind = SUPER_SHIFT, R, exec, sh ~/.config/hypr/launch_waybar.sh --reload && pkill hyprpaper && hyprpaper

# Monitor hotplug integration
exec-once = ~/.config/hypr/scripts/monitor-waybar-handler.sh
# $HOME/.config/hypr/launch_waybar.sh
exec-once = hypridle & mako
exec-once = hyprpaper
# bind = SUPER SHIFT, P, exec, pkill hyprpaper && hyprpaper
