
#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = sh ~/.config/hypr/launch_waybar.sh 

# Waybar reload binds
bind = SUPER_SHIFT, R, exec, sh ~/.config/hypr/launch_waybar.sh --reload
bind = SUPER_SHIFT, W, exec, pkill waybar && sleep 0.5 && ~/.config/waybar/launch_waybar.sh

# Monitor hotplug integration
exec-once = ~/.config/hypr/scripts/monitor-waybar-handler.sh
# $HOME/.config/hypr/launch_waybar.sh
exec-once = hypridle & mako
exec-once = hyprpaper
